version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
